In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder
import pickle

In [5]:
#file got read by pandas
my_file=pd.read_csv('Churn_Modelling.csv')
my_file.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
#dropping values
data_drop=my_file.drop(['RowNumber','CustomerId','Surname'],axis=1)
data_drop.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
label_encoder=LabelEncoder()
data_drop['Gender']=label_encoder.fit_transform(data_drop['Gender'])
data_drop.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [8]:
#one hot encoded the geography and got the features out 
hot_encoder=OneHotEncoder()
one_hot_encoded=hot_encoder.fit_transform(data_drop[['Geography']]).toarray()
sep_names=hot_encoder.get_feature_names_out(['Geography'])
one_hot_encoded
sep_names

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
#making a data frame of both and merging this with old one
new_data=pd.DataFrame(one_hot_encoded,columns=sep_names)
new_data

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
result=pd.concat([data_drop.drop(['Geography'],axis=1),new_data],axis=1)
result.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
import pickle
with open('label_encoder.pkl','wb') as file:
    pickle.dump(label_encoder,file)
with  open('hot_encoder.pkl','wb') as file:
    pickle.dump(hot_encoder,file)

In [14]:
#splitiing into independent and dependent features
x=result.drop(['Exited'],axis=1)
y=result['Exited']
x

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,1.0,0.0,0.0

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
standard_scalar=StandardScaler()
x_train=standard_scalar.fit_transform(x_train)
x_test=standard_scalar.transform(x_test)

In [18]:
import pickle
with open('standard_scaler.pkl','wb') as file:
    pickle.dump(standard_scalar,file)

IMPLEMENTATION  ON THE MODEL

In [13]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

WARNING:tensorflow:From c:\Users\DELL\Desktop\project\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [14]:
x_train.shape[1]

12

In [18]:
#creating hidden layes
model=Sequential([
Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
Dense(32,activation='relu'),
Dense(1,activation='sigmoid')
])

In [20]:
#compling the model
import tensorflow as tf
loss=tf.keras.losses.BinaryCrossentropy()
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [21]:
#setting up tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [22]:
#set up early stop
Early_Stopping=EarlyStopping(monitor='val-loss',patience=10,restore_best_weights=True)

In [ ]:
#train the model 
history=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,Early_Stopping]
)

Epoch 1/100
240/250 [===========================>..] - ETA: 0s - loss: 0.2558 - accuracy: 0.8911WARNING:tensorflow:Early stopping conditioned on metric `val-loss` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
250/250 [==============================] - 1s 5ms/step - loss: 0.2558 - accuracy: 0.8911 - val_loss: 0.4466 - val_accuracy: 0.8485
Epoch 2/100
239/250 [===========================>..] - ETA: 0s - loss: 0.2566 - accuracy: 0.8882WARNING:tensorflow:Early stopping conditioned on metric `val-loss` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
250/250 [==============================] - 1s 5ms/step - loss: 0.2568 - accuracy: 0.8878 - val_loss: 0.4557 - val_accuracy: 0.8460
Epoch 3/100
246/250 [============================>.] - ETA: 0s - loss: 0.2572 - accuracy: 0.8892WARNING:tensorflow:Early stopping conditioned on metric `val-loss` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
250/250 [==============================] - 1s 6ms/step - loss: 0.2575 - accuracy: 0.8892 - val_loss: 0.4589 - val_accuracy: 0.8580
Epoch 4/100
250/250 [==============================] - ETA: 0s - loss: 0.2566 - accuracy: 0.8886WARNING:tensorflow:Early stopping conditioned on metric `val-loss` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
250/250 [==============================] - 1s 5ms/step - loss: 0.2566 - accuracy: 0.8886 - val_loss: 0.4631 - val_accuracy: 0.8425
Epoch 5/100
242/250 [============================>.] - ETA: 0s - loss: 0.2510 - accuracy: 0.8919WARNING:tensorflow:Early stopping conditioned on metric `val-loss` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
250/250 [==============================] - 1s 5ms/step - loss: 0.2505 - accuracy: 0.8921 - val_loss: 0.4715 - val_accuracy: 0.8490
Epoch 6/100
247/250 [============================>.] - ETA: 0s - loss: 0.2517 - accuracy: 0.8926

KeyboardInterrupt:

In [23]:
model.save('model.h5')

c:\Users\DELL\Desktop\project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [ ]:
#load tensorboard
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [ ]:

%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 13808), started 0:00:40 ago. (Use '!kill 13808' to kill it.)